# Converting categorial values to numbers is called encoding#

In [2]:
# ordinal
# nominal values
# types of encoding 
# 1 hot encoding for nominal ctaegorical values
# ordinal encoding 
# label encoding

# ordinal category follows order

# Ordinal encoding

In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [4]:
df = pd.read_csv('titanic_data_updated.csv') 
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,no,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,no,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

In [6]:
# x er bhitor amra features raki 
X = df.drop(['Survived'],axis=1)
X

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0     third    male  22.0      1      0   7.2500   NaN        S
1     first  female  38.0      1      0  71.2833   C85        C
2     third  female  26.0      0      0   7.9250   NaN        S
3     first  female  35.0      1      0  53.1000  C123        S
4     third    male  35.0      0      0   8.0500   NaN        S
..      ...     ...   ...    ...    ...      ...   ...      ...
886  second    male  27.0      0      0  13.0000   NaN        S
887   first  female  19.0      0      0  30.0000   B42        S
888   third  female   NaN      1      2  23.4500   NaN        S
889   first    male  26.0      0      0  30.0000  C148        C
890   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 8 columns]

In [7]:
# target column 
y = df['Survived'] 
y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare    Cabin Embarked
331   first    male  45.5      0      0   28.5000     C124        S
733  second    male  23.0      0      0   13.0000      NaN        S
382   third    male  32.0      0      0    7.9250      NaN        S
704   third    male  26.0      1      0    7.8542      NaN        S
813   third  female   6.0      4      2   31.2750      NaN        S
..      ...     ...   ...    ...    ...       ...      ...      ...
106   third  female  21.0      0      0    7.6500      NaN        S
270   first    male   NaN      0      0   31.0000      NaN        S
860   third    male  41.0      2      0   14.1083      NaN        S
435   first  female  14.0      1      2  120.0000  B96 B98        S
102   first    male  21.0      0      1   77.2875      D26        S

[712 rows x 8 columns]