# Converting categorial values to numbers is called encoding#

In [2]:
# ordinal
# nominal values
# types of encoding 
# 1 hot encoding for nominal ctaegorical values
# ordinal encoding 
# label encoding

# ordinal category follows order

# Ordinal encoding

In [36]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [37]:
df = pd.read_csv('titanic_data_updated.csv') 
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,no,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,no,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [38]:
df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

In [39]:
# x er bhitor amra features raki 
X = df.drop(['Survived'],axis=1)
X

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0     third    male  22.0      1      0   7.2500   NaN        S
1     first  female  38.0      1      0  71.2833   C85        C
2     third  female  26.0      0      0   7.9250   NaN        S
3     first  female  35.0      1      0  53.1000  C123        S
4     third    male  35.0      0      0   8.0500   NaN        S
..      ...     ...   ...    ...    ...      ...   ...      ...
886  second    male  27.0      0      0  13.0000   NaN        S
887   first  female  19.0      0      0  30.0000   B42        S
888   third  female   NaN      1      2  23.4500   NaN        S
889   first    male  26.0      0      0  30.0000  C148        C
890   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 8 columns]

In [40]:
# target column 
y = df['Survived'] 
y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object

In [41]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [42]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare    Cabin Embarked
331   first    male  45.5      0      0   28.5000     C124        S
733  second    male  23.0      0      0   13.0000      NaN        S
382   third    male  32.0      0      0    7.9250      NaN        S
704   third    male  26.0      1      0    7.8542      NaN        S
813   third  female   6.0      4      2   31.2750      NaN        S
..      ...     ...   ...    ...    ...       ...      ...      ...
106   third  female  21.0      0      0    7.6500      NaN        S
270   first    male   NaN      0      0   31.0000      NaN        S
860   third    male  41.0      2      0   14.1083      NaN        S
435   first  female  14.0      1      2  120.0000  B96 B98        S
102   first    male  21.0      0      1   77.2875      D26        S

[712 rows x 8 columns]

In [43]:
from sklearn.preprocessing import OrdinalEncoder 

pclass_encoder = OrdinalEncoder(categories=[['third','second','first']])

pclass_encoder.fit(X_train[['Pclass']])

#transform 

X_train['encoded_pclass']= pclass_encoder.transform(X_train[['Pclass']]).ravel() 
X_test['encoded_pclass']= pclass_encoder.transform(X_test[['Pclass']]).ravel()


X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,encoded_pclass
331,first,male,45.5,0,0,28.5000,C124,S,2.0
733,second,male,23.0,0,0,13.0000,NaN,S,1.0
382,third,male,32.0,0,0,7.9250,NaN,S,0.0
704,third,male,26.0,1,0,7.8542,NaN,S,0.0
813,third,female,6.0,4,2,31.2750,NaN,S,0.0
...,...,...,...,...,...,...,...,...,...
106,third,female,21.0,0,0,7.6500,NaN,S,0.0
270,first,male,NaN,0,0,31.0000,NaN,S,2.0
860,third,male,41.0,2,0,14.1083,NaN,S,0.0
435,first,female,14.0,1,2,120.0000,B96 B98,S,2.0
102,first,male,21.0,0,1,77.2875,D26,S,2.0

In [44]:
from sklearn.preprocessing import OneHotEncoder 

sex_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas') 

sex_ohe.fit(X_train[['Sex']]) 

encoded_df = sex_ohe.transform(X_train[['Sex']])
X_train = pd.concat([X_train,encoded_df],axis=1)

In [50]:
embarked_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas') 

embarked_ohe.fit(X_train[['Embarked']]) 
encoded_embarked = embarked_ohe.transform(X_train[['Embarked']]) 

X_train = pd.concat([X_train,encoded_embarked], axis=1) 
X_train

KeyError: "None of [Index(['Embarked'], dtype='object')] are in the [columns]"

In [51]:
# transforming test data
encoded_embarked = embarked_ohe.transform(X_test[['Embarked']]) 
X_test = pd.concat([X_test,encoded_embarked], axis=1)

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [52]:
X_train.drop(['Pclass','Sex','Embarked'], axis=1, inplace=True)

KeyError: "['Pclass', 'Sex', 'Embarked'] not found in axis"

In [48]:
X_train

,Age,SibSp,Parch,Fare,Cabin,encoded_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
331,45.5,0,0,28.5000,C124,2.0,0.0,1.0,0.0,0.0,1.0,0.0
733,23.0,0,0,13.0000,NaN,1.0,0.0,1.0,0.0,0.0,1.0,0.0
382,32.0,0,0,7.9250,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
704,26.0,1,0,7.8542,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
813,6.0,4,2,31.2750,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
106,21.0,0,0,7.6500,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0
270,NaN,0,0,31.0000,NaN,2.0,0.0,1.0,0.0,0.0,1.0,0.0
860,41.0,2,0,14.1083,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
435,14.0,1,2,120.0000,B96 B98,2.0,1.0,0.0,0.0,0.0,1.0,0.0
102,21.0,0,1,77.2875,D26,2.0,0.0,1.0,0.0,0.0,1.0,0.0

In [49]:
X_test

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,encoded_pclass
709,third,male,NaN,1,1,15.2458,NaN,C,0.0
439,second,male,31.0,0,0,10.5000,NaN,S,1.0
840,third,male,20.0,0,0,7.9250,NaN,S,0.0
720,second,female,6.0,0,1,33.0000,NaN,S,1.0
39,third,female,14.0,1,0,11.2417,NaN,C,0.0
...,...,...,...,...,...,...,...,...,...
433,third,male,17.0,0,0,7.1250,NaN,S,0.0
773,third,male,NaN,0,0,7.2250,NaN,C,0.0
25,third,female,38.0,1,5,31.3875,NaN,S,0.0
84,second,female,17.0,0,0,10.5000,NaN,S,1.0
10,third,female,4.0,1,1,16.7000,G6,S,0.0